# # Your workflow name.
# name: Deploy Infrastructure to Heroku.

# # Run workflow on every push to main branch.
# on:
#   push:
#     paths:
#     - 'infrastructure/**'

# # Your workflows jobs.
# jobs:
#   terraform:
#     runs-on: ubuntu-latest
#     steps:
#       # Check-out your repository.
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Terraform Init
#         uses: hashicorp/terraform-github-actions/init@v0.4.0
#         env:
#           TF_VAR_HEROKU_API_KEY: ${{ secrets.TF_VAR_HEROKU_API_KEY }}

#       - name: Terraform Validate
#         uses: hashicorp/terraform-github-actions/validate@v0.3.7
#         env:
#           TF_VAR_HEROKU_API_KEY: ${{ secrets.TF_VAR_HEROKU_API_KEY }}
      
#       - name: Terraform Apply
#         uses: hashicorp/terraform-github-actions/apply@v0.4.0
#         env:
#           TF_VAR_HEROKU_API_KEY: ${{ secrets.TF_VAR_HEROKU_API_KEY }}